apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: eric-enm-common-helmchart-library.enabled
  name: eric-enm-common-helmchart-library
  repository: https://arm.epk.ericsson.se/artifactory/proj-enm-helm/
  version: 1.55.0-5
description: A Helm chart for log transformer integration certificates
name: eric-enm-int-log-transformer-certs
version: 1.1.0